### Uses the REST Client plugin for VS Code

GET http://{{host}}/api/devices
Authorization: Basic {{user}}:{{pwd}}

###
GET http://{{host}}/api/devices?interface=quickApp
Authorization: Basic {{user}}:{{pwd}}

###
GET http://{{host}}/api/globalVariables/A
Authorization: Basic {{user}}:{{pwd}}

###
POST http://{{host}}/api/plugins/publishEvent HTTP/1.1
content-type: application/json
Authorization: Basic {{user}}:{{pwd}}

{
    "type": "centralSceneEvent",
    "source": 5000,
    "data": { "keyId": 1, "keyAttribute": "Pressed" }
}

###
POST http://{{host}}/api/proxy?url=http://localhost:11112/api/plugins/publishEvent HTTP/1.1
content-type: application/json
Authorization: Basic {{user}}:{{pwd}}

{
    "type": "centralSceneEvent",
    "source": 5000,
    "data": { "keyId": 1, "keyAttribute": "Pressed" }
}
